#############################################################################
# Makefile for building: OS_Simulatorr
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mon Nov 10 17:04:43 2014
# Project:  OS_Simulatorr.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile OS_Simulatorr.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		os_sim.cpp \
		fcfs.cpp \
		sjf.cpp \
		Sched.cpp \
		prority.cpp \
		rr.cpp moc_os_sim.cpp \
		moc_fcfs.cpp \
		moc_sjf.cpp \
		moc_prority.cpp \
		moc_rr.cpp
OBJECTS       = main.o \
		os_sim.o \
		fcfs.o \
		sjf.o \
		Sched.o \
		prority.o \
		rr.o \
		moc_os_sim.o \
		moc_fcfs.o \
		moc_sjf.o \
		moc_prority.o \
		moc_rr.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		OS_Simulatorr.pro
QMAKE_TARGET  = OS_Simulatorr
DESTDIR       = 
TARGET        = OS_Simulatorr

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_os_sim.h ui_fcfs.h ui_sjf.h ui_prority.h ui_rr.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OS_Simulatorr.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile OS_Simulatorr.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile OS_Simulatorr.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/OS_Simulatorr1.0.0 || $(MKDIR) .tmp/OS_Simulatorr1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/OS_Simulatorr1.0.0/ && $(COPY_FILE) --parents os_sim.h fcfs.h Sched.h sjf.h prority.h rr.h .tmp/OS_Simulatorr1.0.0/ && $(COPY_FILE) --parents main.cpp os_sim.cpp fcfs.cpp sjf.cpp Sched.cpp prority.cpp rr.cpp .tmp/OS_Simulatorr1.0.0/ && $(COPY_FILE) --parents os_sim.ui fcfs.ui sjf.ui prority.ui rr.ui .tmp/OS_Simulatorr1.0.0/ && (cd `dirname .tmp/OS_Simulatorr1.0.0` && $(TAR) OS_Simulatorr1.0.0.tar OS_Simulatorr1.0.0 && $(COMPRESS) OS_Simulatorr1.0.0.tar) && $(MOVE) `dirname .tmp/OS_Simulatorr1.0.0`/OS_Simulatorr1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/OS_Simulatorr1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_os_sim.cpp moc_fcfs.cpp moc_sjf.cpp moc_prority.cpp moc_rr.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_os_sim.cpp moc_fcfs.cpp moc_sjf.cpp moc_prority.cpp moc_rr.cpp
moc_os_sim.cpp: os_sim.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) os_sim.h -o moc_os_sim.cpp

moc_fcfs.cpp: Sched.h \
		fcfs.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) fcfs.h -o moc_fcfs.cpp

moc_sjf.cpp: Sched.h \
		sjf.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sjf.h -o moc_sjf.cpp

moc_prority.cpp: Sched.h \
		prority.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) prority.h -o moc_prority.cpp

moc_rr.cpp: Sched.h \
		rr.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) rr.h -o moc_rr.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_os_sim.h ui_fcfs.h ui_sjf.h ui_prority.h ui_rr.h
compiler_uic_clean:
	-$(DEL_FILE) ui_os_sim.h ui_fcfs.h ui_sjf.h ui_prority.h ui_rr.h
ui_os_sim.h: os_sim.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic os_sim.ui -o ui_os_sim.h

ui_fcfs.h: fcfs.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic fcfs.ui -o ui_fcfs.h

ui_sjf.h: sjf.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic sjf.ui -o ui_sjf.h

ui_prority.h: prority.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic prority.ui -o ui_prority.h

ui_rr.h: rr.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic rr.ui -o ui_rr.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp os_sim.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

os_sim.o: os_sim.cpp os_sim.h \
		ui_os_sim.h \
		fcfs.h \
		Sched.h \
		sjf.h \
		prority.h \
		rr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o os_sim.o os_sim.cpp

fcfs.o: fcfs.cpp fcfs.h \
		Sched.h \
		ui_fcfs.h \
		os_sim.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fcfs.o fcfs.cpp

sjf.o: sjf.cpp sjf.h \
		Sched.h \
		ui_sjf.h \
		os_sim.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sjf.o sjf.cpp

Sched.o: Sched.cpp Sched.h \
		os_sim.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Sched.o Sched.cpp

prority.o: prority.cpp prority.h \
		Sched.h \
		ui_prority.h \
		os_sim.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prority.o prority.cpp

rr.o: rr.cpp rr.h \
		Sched.h \
		ui_rr.h \
		os_sim.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rr.o rr.cpp

moc_os_sim.o: moc_os_sim.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_os_sim.o moc_os_sim.cpp

moc_fcfs.o: moc_fcfs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fcfs.o moc_fcfs.cpp

moc_sjf.o: moc_sjf.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sjf.o moc_sjf.cpp

moc_prority.o: moc_prority.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_prority.o moc_prority.cpp

moc_rr.o: moc_rr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rr.o moc_rr.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

